/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jycessing_jni_OSX */

#ifndef _Included_jycessing_jni_OSX
#define _Included_jycessing_jni_OSX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jycessing_jni_OSX
 * Method:    activateIgnoringOtherApps
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jycessing_jni_OSX_activateIgnoringOtherApps
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
